export const seoKeywords = [
    "zero latency",
    "zero latency vr",
    "zerolatencyvr",
    "zero latency vr webster",
    "zero latency texas",
    "zero latency price",
    "zero latency review",
    "zero latency vr near me",
    "vr experiences",
    "virtual reality experience",
    "vr arcade",
    "vr arena",
    "virtual reality arcade",
    "virtual reality arena",
    "vr arcade near me",
    "virtual reality arcade near me",
    "virtual reality Webster",
    "vr experience Webster",
    "vr experience near me",
    "vr arena near me",
    "virtual reality arena near me",
    "virtual reality games webster",
    "vr arcade webster",
    "vr arena webster",
    "Immersive Experience",
    "Immersive Experience webster",
    "immersive vr",
    "free roam vr",
    "virtual reality gaming",
    "virtual reality near me",
    "vr gaming place",
    "vr places near me",
    "VR lounge",
    "esports near me",
    "far cry",
    "far cry 3",
    "far cry virtual reality",
    "far cry vr",
    "virtual reality esports",
    "virtual reality games webster",
    "virtual reality games texas",
    "virtual reality pvp",
    "virtual reality shooter game",
    "virtual reality tournament",
    "vr esports",
    "vr games",
    "vr player vs player",
    "vr pvp",
    "vr shooter game",
    "vr tournament",
    "zombie virtual reality",
    "zombie virtual reality game",
    "zombie virtual reality near me",
    "zombie vr",
    "zombie vr game",
    "zombie vr near me",
    "paintball webster",
    "laser tag",
    "axe throwing webster",
    "axe throwing near me",
    "virtual reality laser tag",
    "vr laser tag",
    "virtual reality laser tag near me",
    "vr laser tag",
    "vr laser tag near me",
    "vr escape room",
    "things to do webster",
    "things to do houston",
    "fun group activities",
    "fun group activity",
    "fun weekend activities",
    "things to do near me",
    "fun evening activities",
    "things to do group",
    "fun group activity webster",
    "fun group activity houston",
    "fun group activity near me",
    "things to do group near me",
    "things to do group webster",
    "team event ideas",
    "bachelor party ideas",
    "bachelor party venue",
    "bachelor party webster",
    "bachelor party houston",
    "birthday party activities",
    "birthday party event",
    "bachelor party event no strippers",
    "unique bachelor event no strippers",
    "team building activity webster",
    "team building venue webster",
    "team building ideas webster",
    "team building activity houston",
    "team building venue houston",
    "team building ideas houston",
    "vr teambuilding",
    "company team activities",
    "team building event",
    "unique corporate Christmas party",
    "corporate event ideas",
    "team building ideas",
    "unique christmas gift",
    "gift for teenagers",
    "unique gift for gamers",
    "vr gift cards",
    "vr gift vouchers",
    "gift card for teenagers",
    "unique christmas gift for husband",
    "Zero Latency Webster",
    "VR Gaming Webster TX",
    "Free Roam VR Houston",
    "Virtual Reality Arena",
    "VR Games Texas",
    "Far Cry VR Webster",
    "Undead Arena VR",
    "Space Marine VR",
    "Team Building VR",
    "Bachelor Party VR",
  ];